name: Build and Deploy

on:
  push:
    branches:
      - master
      - develop

jobs:
  jekyll-build:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 set up
        uses: actions/checkout@v4
      - name: 💎 set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - run:  yes | gem update --system --force
      - name: 🔨 install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
      - name: cache HTMLProofer
        id: cache-htmlproofer
        uses: actions/cache@v4
        with:
          path: tmp/.htmlproofer
          key: ${{ runner.os }}-htmlproofer
      - name: run tests
        run: |
          bundle exec htmlproofer ./_site\
            --only-4xx\
            --assume-extension .html\
            --no-enforce-https\
            --ignore-missing-alt\
            --ignore-urls '/vimeo.com/,/twitter.com/,/instagram.com/'\
            --swap-urls 'https?\:\/\/alexwalker\.co:'\
            --cache '{ "timeframe": { "external": "30d" } }'
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site
  deploy:
    runs-on: ubuntu-latest
    needs: [jekyll-build]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download build result
        uses: actions/download-artifact@v3
        with:
          name: site
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan ssh.nickwalker.us >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: 🚀 deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: "rsync -havz * www-data@ssh.nickwalker.us:/var/www/alexwalker.co/"
      - name: purge Cloudflare cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}
  deploy-staging:
    runs-on: ubuntu-latest
    needs: [jekyll-build]
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Download build result
        uses: actions/download-artifact@v3
        with:
          name: site
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan ssh.nickwalker.us >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: 🚀 deploy to staging
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: "rsync -havz --delete ./ www-data@ssh.nickwalker.us:/var/www/testing.alexwalker.co/ --exclude=/.well-known"
